[project]
name = "kto-api-and-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=3.7.1",
    "ruff>=0.14.9",
]
